name: my-first-action

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: print Hello
        run : echo "Hello. I'm your first action"
        
      - name: Checkout the sources
        uses: actions/checkout@v2

      - name: run script
        run: ls -la
