name: my-first-action

on:
  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: print Hello
        run: echo "Hello. I'm your first action"
        
      - name: Checkout the sources
        uses: actions/checkout@v2
        
      - name: macking test files
        run: |
          chmod +x dir_macker
          ./dir_macker
      
      - name: run script
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh -r

      - name: show result on folders
        run: tree
