name: my-first-action

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: print Hello
        run : echo "Hello. I'm your first action"

      - name: run script
        run: ls -la
