name: my-first-action

on:
  push:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: print Hello
        run: echo "Hello. I'm your first action"
        
      - name: Checkout the sources
        uses: actions/checkout@v2
      
      - name: run script
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh -r

      - name: show result on folders
        run: tree
        
      - name: run script
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh -c
          
      - name: show result on folders
        run: tree
